#
# Copyright (C) 2012 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is generated by device/huawei/u8800/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/pulled/system/lib/libnv.so:obj/lib/libnv.so \
	vendor/huawei/u8800/pulled/system/lib/liboncrpc.so:obj/lib/liboncrpc.so \
	vendor/huawei/u8800/pulled/system/lib/libaudcal.so:obj/lib/libaudcal.so \
	vendor/huawei/u8800/pulled/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/huawei/u8800/pulled/system/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/pulled/system/bin/rmt_storage:system/bin/rmt_storage \
	vendor/huawei/u8800/pulled/system/bin/cnd:system/bin/cnd \
	vendor/huawei/u8800/pulled/system/bin/netmgrd:system/bin/netmgrd \
	vendor/huawei/u8800/pulled/system/bin/qmuxd:system/bin/qmuxd \
	vendor/huawei/u8800/pulled/system/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
	vendor/huawei/u8800/pulled/system/lib/libauth.so:system/lib/libauth.so \
	vendor/huawei/u8800/pulled/system/lib/libcm.so:system/lib/libcm.so \
	vendor/huawei/u8800/pulled/system/lib/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/u8800/pulled/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/u8800/pulled/system/lib/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/u8800/pulled/system/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/u8800/pulled/system/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
	vendor/huawei/u8800/pulled/system/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
	vendor/huawei/u8800/pulled/system/lib/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/u8800/pulled/system/lib/libidl.so:system/lib/libidl.so \
	vendor/huawei/u8800/pulled/system/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
	vendor/huawei/u8800/pulled/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/u8800/pulled/system/lib/libnv.so:system/lib/libnv.so \
	vendor/huawei/u8800/pulled/system/lib/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/u8800/pulled/system/lib/libpbmlib.so:system/lib/libpbmlib.so \
	vendor/huawei/u8800/pulled/system/lib/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/u8800/pulled/system/lib/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/u8800/pulled/system/lib/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/u8800/pulled/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/u8800/pulled/system/lib/libwms.so:system/lib/libwms.so \
	vendor/huawei/u8800/pulled/system/lib/libwmsts.so:system/lib/libwmsts.so \
	vendor/huawei/u8800/pulled/recovery/root/sbin/rmt_storage:recovery/root/sbin/rmt_storage \
	vendor/huawei/u8800/pulled/system/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/huawei/u8800/pulled/system/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/u8800/pulled/system/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
	vendor/huawei/u8800/pulled/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	vendor/huawei/u8800/pulled/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	vendor/huawei/u8800/pulled/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	vendor/huawei/u8800/pulled/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/huawei/u8800/pulled/system/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
	vendor/huawei/u8800/pulled/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	vendor/huawei/u8800/pulled/system/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
	vendor/huawei/u8800/pulled/system/lib/libC2D2.so:system/lib/libC2D2.so \
	vendor/huawei/u8800/pulled/system/lib/libgsl.so:system/lib/libgsl.so \
	vendor/huawei/u8800/pulled/system/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
	vendor/huawei/u8800/pulled/system/lib/libOpenCL.so:system/lib/libOpenCL.so \
	vendor/huawei/u8800/pulled/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
	vendor/huawei/u8800/pulled/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
	vendor/huawei/u8800/pulled/system/etc/firmware/wlan/cfg.dat:system/etc/firmware/wlan/cfg.dat \
	vendor/huawei/u8800/pulled/system/etc/firmware/wlan/qcom_cfg.ini:system/etc/firmware/wlan/qcom_cfg.ini \
	vendor/huawei/u8800/pulled/system/etc/firmware/wlan/qcom_fw.bin:system/etc/firmware/wlan/qcom_fw.bin \
	vendor/huawei/u8800/pulled/system/etc/firmware/wlan/qcom_wapi_fw.bin:system/etc/firmware/wlan/qcom_wapi_fw.bin \
	vendor/huawei/u8800/pulled/system/etc/firmware/wlan/qcom_wlan_nv.bin:system/etc/firmware/wlan/qcom_wlan_nv.bin \
	vendor/huawei/u8800/pulled/system/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
	vendor/huawei/u8800/pulled/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/huawei/u8800/pulled/system/lib/libchromatix_s5k4e1gx_p_default_video.so:system/lib/libchromatix_s5k4e1gx_p_default_video.so \
	vendor/huawei/u8800/pulled/system/lib/libchromatix_s5k4e1gx_p_preview.so:system/lib/libchromatix_s5k4e1gx_p_preview.so \
	vendor/huawei/u8800/pulled/system/lib/libchromatix_ov5647_sunny_preview.so:system/lib/libchromatix_ov5647_sunny_preview.so \
	vendor/huawei/u8800/pulled/system/lib/libchromatix_ov5647_sunny_default_video.so:system/lib/libchromatix_ov5647_sunny_default_video.so \
	vendor/huawei/u8800/pulled/system/lib/libgemini.so:system/lib/libgemini.so \
	vendor/huawei/u8800/pulled/system/lib/libmmipl.so:system/lib/libmmipl.so \
	vendor/huawei/u8800/pulled/system/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/huawei/u8800/pulled/system/lib/liboemcamera.so:system/lib/liboemcamera.so
