#
# Copyright (C) 2012 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is generated by device/huawei/u8800/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/proprietary/pulled/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
	vendor/huawei/u8800/proprietary/pulled/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/u8800/proprietary/pulled/bin/rmt_storage:system/bin/rmt_storage \
	vendor/huawei/u8800/proprietary/pulled/bin/cnd:system/bin/cnd \
	vendor/huawei/u8800/proprietary/pulled/bin/netmgrd:system/bin/netmgrd \
	vendor/huawei/u8800/proprietary/pulled/bin/qmuxd:system/bin/qmuxd \
	vendor/huawei/u8800/proprietary/pulled/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
	vendor/huawei/u8800/proprietary/pulled/bin/rild:system/bin/rild \
	vendor/huawei/u8800/proprietary/pulled/lib/libril.so:system/lib/libril.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libauth.so:system/lib/libauth.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libcm.so:system/lib/libcm.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libidl.so:system/lib/libidl.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libnv.so:system/lib/libnv.so \
	vendor/huawei/u8800/proprietary/pulled/lib/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libpbmlib.so:system/lib/libpbmlib.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libwms.so:system/lib/libwms.so \
	vendor/huawei/u8800/proprietary/pulled/lib/libwmsts.so:system/lib/libwmsts.so
